import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/redux/providers"; //Provider que englobara la app

export const metadata: Metadata = {
  title: "NextJS - Redux Toolkit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="p-5">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
